### ISSUE TITLE
Error on start quickgui

### ISSUE THREAD

**Issue by thedemonium** [quickemu-project/quickgui#81] opened 2022-08-31 09:25 UTC
Ubuntu 22.04.1 LTS
sudo add-apt-repository ppa:yannick-mauray/quickgui
sudo apt update
sudo apt install quickgui

quickgui
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ProcessException: Not a directory
  Command: quickget list_csv
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      loadOperatingSystems (package:quickgui/main.dart:16)
#5      main (package:quickgui/main.dart:61)
#6      main (file:///home/yannick/quickgui/.dart_tool/flutter_build/generated_main.dart)
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:127)
#8      _rootRun (dart:async/zone.dart:1428)
#9      _CustomZone.run (dart:async/zone.dart:1328)
#10     _runZoned (dart:async/zone.dart:1863)
#11     runZonedGuarded (dart:async/zone.dart:1851)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

sudo apt-cache policy quickgui 
quickgui:
  Installed: 1.2.4-1 jammy1.0
  Candidate: 1.2.4-1 jammy1.0
  Version table:
  1.2.4-1 jammy1.0 500
        500 https://ppa.launchpadcontent.net/yannick-mauray/quickgui/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by iRomanyshyn** [comment] 2022-09-05 09:31
The same here

```./quickgui 
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ProcessException: No such file or directory
  Command: quickget list_csv
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      loadOperatingSystems (package:quickgui/main.dart:16)
#5      main (package:quickgui/main.dart:61)
#6      main (file:///home/yannick/quickgui/.dart_tool/flutter_build/generated_main.dart)
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:127)
#8      _rootRun (dart:async/zone.dart:1428)
#9      _CustomZone.run (dart:async/zone.dart:1328)
#10     _runZoned (dart:async/zone.dart:1863)
#11     runZonedGuarded (dart:async/zone.dart:1851)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)```

**Comment by lucamanga** [comment] 2022-09-19 08:13
Me too on Fedora 36.

**Comment by lucamanga** [comment] 2022-09-19 08:30
I found the fix. You must make the executable 'quickgui' and 'quickemu' available through PATH.

**Comment by flexiondotorg** [comment] 2022-09-20 14:19
Duplicate of #68

**Closed by flexiondotorg** 2022-09-20 14:19 UTC
Labels: duplicate
