### ISSUE TITLE
(Feature Request) Windows or macOS version

### ISSUE THREAD

**Issue by dtantono** [quickemu-project/quickgui#67] opened 2022-02-11 12:34 UTC
Hi
to improve this app popularity. Is this possible to have windows/macOS version for this app?

**Comment by miigotu** [comment] 2022-03-09 05:48
Duplicate of #32 - quickemu does not support it, maybe ask on that repo or use WSL

**Comment by marxjohnson** [comment] 2022-04-19 09:08
Closing this as a duplicate.

**Closed by marxjohnson** 2022-04-19 09:08 UTC
