### ISSUE TITLE
issue cannot change workspace

### ISSUE THREAD

**Issue by jhonoryza** [quickemu-project/quickgui#43] opened 2021-12-02 03:45 UTC
I am using garuda linux, try binary release version 1.1.5, cannot change workspace

**Comment by vgivanovic** [comment] 2021-12-03 01:22
Same here. I'm on Arch Linux and I built my own `quickgui`. I've tried rebuilding, ripgrepping for a file containing part of the incorrect directory and using `strace` to find out where `quickgui` is getting the incorrect filename. So for now, I'm just using `quickget` to get the ISO. I'll try `quickgui` to manage creating and running the Win11 VM.

**Comment by ymauray** [comment] 2021-12-10 00:07
I was not able to reproduce this. The current working directory is stored in local preferences, in ${HOME}/.local/share/quickgui/shared_preferences.json, check to see what value it has there.
Also, in the code, it is set in `downloader_menu.dart`, lines 64 to 83, if you want to tinker with that.

**Comment by flexiondotorg** [comment] 2024-06-26 14:06
Fixed via https://github.com/quickemu-project/quickgui/pull/130

Which makes sure `zenity` is a dependency of quickgui.

**Closed by flexiondotorg** 2024-06-26 14:06 UTC
Labels: keep and eye on it
