### ISSUE TITLE
Add Fedora Support

### ISSUE THREAD

**Issue by rexackermann** [quickemu-project/quickgui#95] opened 2022-12-22 03:40 UTC
Would be a good thing I guess.

**Comment by ItsRogueRen** [comment] 2024-02-20 00:07
> #97 Adds both Fedora (RPM) and AppImage support 😇

This is not a reasonable solution for rpm/appimages as it requires setting up a development environment that gets out of hand VERY quickly if you are not a developer. Always assume the end user is an idiot that has no idea how a computer works.

**Comment by flexiondotorg** [comment] 2024-06-25 12:39
Duplicate of #97

**Closed by flexiondotorg** 2024-06-25 12:39 UTC
Labels: duplicate
